# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "talos-systems/sidero"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.5.4"

pre_release = false

preface = """\
"""

[notes]

   [notes.talos]
        title = "Talos 1.2.x Support"
        description = """\
This release of Sidero brings compatibility with Talos v1.2.x release series.
"""

