# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "talos-systems/sidero"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.5.0"

pre_release = true

preface = """\
"""

[notes]
    [notes.metalsiderodev]
        title = "New API Version for `metal.sidero.dev` Resources"
        description = """\
Resources under `metal.sidero.dev` (`Server`, `ServerClass`, `Environment`) now have a new version `v1alpha2`.
Old version `v1alpha1` is still supported, but it is recommended to update templates to use the new resource version.

#### `Server` Changes

Hardware information was restructured and extended when compared with `v1alpha1`:

* `.spec.systemInformation` -> `.spec.hardware.system`
* `.spec.cpu` -> `.spec.hardware.compute.processors[]`

#### `ServerClass` Changes

* `.spec.qualifiers.systemInformation` -> `.spec.qualifiers.system`
* `.spec.qualifiers.cpu` -> `.spec.qualifiers.hardware.compute.processors[]`
"""

    [notes.machineconfig]
        title = "Metadata Server"
        description = """\
Sidero Metadata Server no longer depends on the version of Talos machinery library it is built with.
Sidero should be able to process machine config for future versions of Talos.
"""

    [notes.agent]
        title = "Sidero Agent"
        description = """\
Sidero Agent now runs DHCP client in the userland, on the link which was used to PXE boot the machine.
This allows to run Sidero Agent on the machine with several autoconfigured network interfaces, when one of them is used for the management network.
"""
