# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "talos-systems/sidero"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.5.1"

pre_release = false

preface = """\
"""

[notes]

    [notes.wg-endpoint-resolution]
        title = "Hostname Resolution for Siderolink Wireguard Endpoint"
        description = """\
It is now possible to specify a hostname as the wireguard endpoint (`SIDERO_CONTROLLER_MANAGER_SIDEROLINK_ENDPOINT`).
Sidero will attempt to resolve the hostname to an IP address on startup and use the resolved IP.
"""
