# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "talos-systems/sidero"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.6.0"

pre_release = false

preface = """\
"""

[notes]

    [notes.dhcpproxy]
        title = "DHCP Proxy"
        description = """\
Sidero Controller Manager now provides a way to disable DHCP Proxy with `SIDERO_CONTROLLER_MANAGER_DISABLE_DHCP_PROXY` variable on
installation.
"""
