# commit to be tagged for new release
commit = "HEAD"

project_name = "Sidero"
github_repo = "talos-systems/sidero"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.5.2"

pre_release = false

preface = """\
"""

[notes]

    [notes.talos]
        title = "Talos 1.1.x Support"
        description = """\
This release of Sidero brings compatibility with Talos v1.1.x release series.
"""

    [notes.bdro]
        title = "Sidero Agent and Read-Only Blockdevices"
        description = """\
Sidero Agent now correctly skips read-only blockdevices when resetting the machine.
"""
